describe("init", function()
  it("can setup repeatedly and create commands", function()
    local docker = require("neovim-docker")
    docker.setup({ keymaps = { enabled = false } })
    docker.setup({ keymaps = { enabled = false } })

    truthy(vim.fn.exists(":DockerContainers") == 2)
    truthy(vim.fn.exists(":DockerAction") == 2)
    truthy(vim.fn.exists(":DockerTelescopeContainers") == 2)
    truthy(vim.fn.exists(":DockerComposeProjects") == 2)
    truthy(vim.fn.exists(":DockerComposeCwd") == 2)
    truthy(vim.fn.exists(":DockerComposeFiles") == 2)
    truthy(vim.fn.exists(":DockerComposeContainers") == 2)
    truthy(vim.fn.exists(":DockerSearch") == 2)
    truthy(vim.fn.exists(":DockerImageHistory") == 2)
    truthy(vim.fn.exists(":DockerRegistryStatus") == 2)
  end)
end)
